### ISSUE TITLE
Cannot post message

### ISSUE THREAD

**Issue by Connection-Point** [IdoBouskila/live-chat-app#1]
Hi there, i dont see any response from server's side command console when i try to enter a room or post message. Message sent also cannot be posted. Could you please try too look into this? Or maybe we can connect with each other through any social media. Thanks

**Comment by IdoBouskila** [comment]
Hello! If you didn't change my code you shouldn't see any response from the server in the console except when running the server.
https://github.com/IdoBouskila/live-chat-app/blob/4b4fa81043be8fc111ac730831c7fdc493b05fc3/server/server.js#L11-L13

**Comment by Connection-Point** [comment]
> Hello! If you didn't change my code you shouldn't see any response from the server in the console except when running the server.
> https://github.com/IdoBouskila/live-chat-app/blob/4b4fa81043be8fc111ac730831c7fdc493b05fc3/server/server.js#L11-L13

Yup, I just perform the npm install for both the server and client. After that I made a .env file with the example you provided. Both the port and react_app_server was 5000. 

But eventually, the message cannot be posted too.

**Comment by IdoBouskila** [comment]
@Connection-Point After installing the dependencies, are you sure that you run the server as the `README` explain?
https://github.com/IdoBouskila/live-chat-app/blob/4b4fa81043be8fc111ac730831c7fdc493b05fc3/README.md?plain=1#L29-L31

**Comment by Connection-Point** [comment]
> @Connection-Point After installing the dependencies, are you sure that you run the server as the `README` explain?
> https://github.com/IdoBouskila/live-chat-app/blob/4b4fa81043be8fc111ac730831c7fdc493b05fc3/README.md?plain=1#L29-L31

Yup, I perform the node server.js and npm run start for client and server as it stated in the readme.

**Comment by IdoBouskila** [comment]
@Connection-Point Interesting, both client and server not running? or just the server?

**Comment by Connection-Point** [comment]
> @Connection-Point Interesting, both client and server not running? or just the server?

I'll attach the picture. Hold on a sec ya.

**Comment by IdoBouskila** [comment]
> > @Connection-Point Interesting, both client and server not running? or just the server?
> 
> I'll attach the picture. Hold on a sec ya.

You got it to work?

**Comment by Connection-Point** [comment]
> > > @Connection-Point Interesting, both client and server not running? or just the server?
> > 
> > I'll attach the picture. Hold on a sec ya.
> 
> You got it to work?

Ahhh yess, sorry for the late reply. I'll close the issue now. Just done configuring the port there, my server port is clashing with the other project  one. Thanks for the guidance 😃
